### ISSUE TITLE
[Fix] 재생여부 초기화 안되는 문제

### ISSUE THREAD

**Issue by YunKi-H** [DeveloperAcademy-POSTECH/2024-MacC-A18-Krabs#311]
## Problem

- [ ] 장단을 재생중에 뒤로가기 버튼을 눌러서 메트로놈 화면에서 나옴
- [ ] 소리 재생은 멈춤
- [ ] 다시 메트로놈 화면으로 들어가면 재생중인 화면으로 표시됨

**Comment by l1004ga** [comment]
엥,,, 너무 크리티컬한 버그인데요...? 언제부터 생겼으려나?

**Comment by YunKi-H** [comment]
ViewModel의 isPlaying이 초기화 안되는거같은데
1. 페이지 나갈때 isPlaying 초기화기능 넣기
2. 애초에 재생중인지 여부를 MetronomeOnOffUseCase와 동기화시켜놓기
이상 두가지 해결방안이 있을거같아요
