### ISSUE TITLE
[Chore] 암호화 알고리즘 사용여부 설정

### ISSUE THREAD

**Issue by YunKi-H** [DeveloperAcademy-POSTECH/2024-MacC-A18-Krabs#319]
## Description

매번 AppstoreConnect에 앱 빌드올리면 뜨는
`수출 규정 관련 문서 누락` 알림을 제거하기 위한 설정을 추가합니다.

## TODO

- [ ] info.plist 에 관련 설정 추가

### ETC 

[블로그](https://whoyoung90.tistory.com/78) 참고

**Comment by l1004ga** [comment]
내용 확인했어요~ 추가하시죠!
